import { existsSync, watch } from 'node:fs';
import { mkdir, writeFile, readFile, rename } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, type ChildProcess } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import type { resolveDirs } from './load-config.js';

type Dirs = ReturnType<typeof resolveDirs>;

export interface ConsoleClientHandle {
  /** No-op in prod mode, which is a one-shot build with nothing left running to stop. */
  stop: () => Promise<void>;
}

export interface BuildConsoleClientOptions {
  watch: boolean;
  mode: 'dev' | 'prod';
}

const NOOP_HANDLE: ConsoleClientHandle = { stop: async () => {} };

/** The framework-owned console client entry (`main.tsx`) and its Tailwind source (`styles.css`) —
 * resolved relative to this module rather than a consumer path, since there's no per-app entry
 * file to author (a consumer's only extension point, `*.form.tsx`, is pulled in through the
 * `ratchet:custom-forms` specifier `main.tsx` imports — see `customFormsPlugin` below — not by
 * writing its own entry). Checks for `main.tsx` first (running from source under Bun, e.g. this
 * repo's own `example/`) and falls back to the compiled `main.js` (running from a published
 * `dist/`, e.g. a real consumer's `node_modules/@egig/ratchet`) — both live one directory up from
 * this file's own location. */
function frameworkConsoleClientDir(): string {
  return path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'console', 'client');
}

function frameworkConsoleEntry(): string {
  const dir = frameworkConsoleClientDir();
  const source = path.join(dir, 'main.tsx');
  return existsSync(source) ? source : path.join(dir, 'main.js');
}

function frameworkCssEntry(): string | null {
  const cssFile = path.join(frameworkConsoleClientDir(), 'styles.css');
  return existsSync(cssFile) ? cssFile : null;
}

/** Resolves the `ratchet:custom-forms` specifier `main.tsx` imports to the consuming project's
 * own generated `<generatedDir>/console-forms.ts` (written by `ratchet generate` — see
 * forms-gen.ts) — a virtual specifier, not a real package, since `main.tsx` lives in the framework
 * and can't hold a relative path to a file that only exists inside whichever consumer project
 * happens to be building it. */
function customFormsPlugin(generatedDir: string): Bun.BunPlugin {
  return {
    name: 'ratchet-custom-forms',
    setup(build) {
      build.onResolve({ filter: /^ratchet:custom-forms$/ }, () => ({
        path: path.join(generatedDir, 'console-forms.ts'),
      }));
    },
  };
}

/** Combines the framework's own `styles.css` (whose `@source "."` scans the framework's console
 * components — see that file) with an `@source` over the consuming project's `modelsDir`, so a
 * `*.form.tsx`'s own Tailwind classes survive the CLI's content scan instead of being silently
 * purged. Written into `generatedDir` (not passed as an in-memory string) because the Tailwind CLI
 * only takes a file path for `--input`. Returns null when the framework has no `styles.css` to
 * wrap (mirrors `frameworkCssEntry`). */
async function writeConsoleCssEntry(dirs: Dirs): Promise<string | null> {
  const frameworkCss = frameworkCssEntry();
  if (!frameworkCss) return null;
  const entryFile = path.join(dirs.generatedDir, 'console-entry.css');
  const content =
    '/* GENERATED by `ratchet build`/`ratchet dev` — do not edit. */\n' +
    `@import ${JSON.stringify(frameworkCss)};\n` +
    `@source ${JSON.stringify(dirs.modelsDir)};\n`;
  await mkdir(dirs.generatedDir, { recursive: true });
  await writeFile(entryFile, content, 'utf8');
  return entryFile;
}

async function hashFile(filePath: string): Promise<string> {
  const content = await readFile(filePath);
  return createHash('sha1').update(content).digest('hex').slice(0, 8);
}

const require = createRequire(import.meta.url);

/** Absolute path to the standalone Tailwind CLI's entry script. `@tailwindcss/cli` is a direct
 * dependency of this package, so it resolves whether it's hoisted to the consumer's top-level
 * `node_modules` or nested under `@egig/ratchet` — unlike `npx tailwindcss`, which fails in a
 * consumer app with "could not determine executable to run" because the CLI is a transitive
 * dependency and its bin is never linked into the consumer's root `node_modules/.bin`. The
 * package only exposes `./package.json` through its `exports`, so resolve that and read the
 * `bin` entry from it, then spawn it directly with `node`. */
function tailwindCliEntry(): string {
  const pkgJsonPath = require.resolve('@tailwindcss/cli/package.json');
  const pkg = require('@tailwindcss/cli/package.json') as { bin: Record<string, string> };
  return path.resolve(path.dirname(pkgJsonPath), pkg.bin.tailwindcss!);
}

function runTailwindOnce(input: string, output: string, minify: boolean): Promise<void> {
  return new Promise((resolve, reject) => {
    const args = [tailwindCliEntry(), '--input', input, '--output', output];
    if (minify) args.push('--minify');
    const child = spawn(process.execPath, args, { stdio: 'inherit' });
    child.on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`tailwindcss exited with code ${code}`))));
    child.on('error', reject);
  });
}

function spawnTailwindWatch(input: string, output: string): ChildProcess {
  return spawn(process.execPath, [tailwindCliEntry(), '--input', input, '--output', output, '--watch=always'], {
    stdio: 'inherit',
  });
}

async function killChild(child: ChildProcess): Promise<void> {
  // Ctrl-C reaches the child directly through the shared terminal process group, so it may
  // already be gone — `exit` has then fired and won't fire again, so waiting on it would hang.
  if (child.exitCode !== null || child.signalCode !== null) return;
  await new Promise<void>((resolve) => {
    child.once('exit', () => resolve());
    child.kill();
  });
}

async function bundleConsoleClient(dirs: Dirs, assetsDir: string, mode: 'dev' | 'prod'): Promise<Bun.BuildArtifact> {
  const result = await Bun.build({
    entrypoints: [frameworkConsoleEntry()],
    outdir: assetsDir,
    naming: mode === 'prod' ? '[dir]/[name]-[hash].[ext]' : '[dir]/[name].[ext]',
    target: 'browser',
    format: 'esm',
    sourcemap: mode === 'dev' ? 'linked' : 'none',
    minify: mode === 'prod',
    plugins: [customFormsPlugin(dirs.generatedDir)],
    define: {
      __CONSOLE_PATH__: JSON.stringify(dirs.consolePath),
      __CONSOLE_BRAND__: JSON.stringify(dirs.brand),
      // `Bun.build`'s automatic JSX transform picks the dev-only `react/jsx-dev-runtime` unless
      // it sees `process.env.NODE_ENV` resolve to `'production'` — mutating the actual env var at
      // call time doesn't reach it (the check runs against the build's own snapshot), so `define`
      // is the reliable lever. Always production here, in both dev and prod mode, matching the
      // previous esbuild-based build (which never opted into the dev JSX transform either).
      'process.env.NODE_ENV': JSON.stringify('production'),
    },
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('Bun.build produced no JS output for the console client entry');
  }
  const jsOutput = result.outputs.find((o) => o.kind === 'entry-point' && o.path.endsWith('.js'));
  if (!jsOutput) throw new Error('Bun.build produced no JS output for the console client entry');
  return jsOutput;
}

/** Bundles the framework's own console client entry with `Bun.build` — every app gets the same
 * console UI (see ConsoleApp.tsx), so this always runs, unconditionally, and the only per-app
 * source it pulls in is whatever `console-forms.ts` (see forms-gen.ts) resolves to via the
 * `ratchet:custom-forms` specifier. Runs Tailwind's standalone CLI against a generated CSS entry
 * (`writeConsoleCssEntry`) that layers a `*.form.tsx` content scan on top of the framework's own
 * `styles.css`, and writes `<generatedDir>/console/manifest.json` mapping logical names to the actual (optionally
 * content-hashed) asset paths. `dirs.consolePath` and `dirs.brand` are inlined into the bundle via
 * `Bun.build`'s `define` (`__CONSOLE_PATH__`/`__CONSOLE_BRAND__`, declared ambiently in
 * src/console/client/env.d.ts) — the client needs them for the router `basename`/API prefix and
 * the sidebar heading respectively, and has no other runtime config channel (it's served as a
 * static bundle, including from a pure edge CDN with no per-request server involved). Changing
 * either therefore requires a rebuild. */
export async function buildConsoleClient(dirs: Dirs, options: BuildConsoleClientOptions): Promise<ConsoleClientHandle> {
  const consoleDir = path.join(dirs.generatedDir, 'console');
  const assetsDir = path.join(consoleDir, 'assets');
  await mkdir(assetsDir, { recursive: true });

  const cssEntry = await writeConsoleCssEntry(dirs);
  const manifest: Record<string, string> = {};

  if (options.mode === 'dev') {
    // Fixed filenames in dev (Q5) — write the manifest once, up front, no metafile parsing needed.
    manifest['main.js'] = 'assets/main.js';
    if (cssEntry) manifest['main.css'] = 'assets/main.css';
    await writeFile(path.join(consoleDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');

    await bundleConsoleClient(dirs, assetsDir, 'dev');

    // `Bun.build` has no incremental watch-context API (unlike esbuild's `ctx.watch()`), so
    // rebuild by hand: watch the framework's own console client source tree and re-run the build
    // on any change, debounced the same way `dev.ts` debounces model-file changes. Also watches
    // the generated `console-forms.ts` (see forms-gen.ts) — `dev.ts`'s own model-file watcher
    // rewrites it whenever a `*.form.tsx` is added/changed/removed, and this is what turns that
    // rewrite into an actual client rebuild (`ratchet:custom-forms` resolves to it — see
    // `customFormsPlugin` above — so its content is exactly what the bundle needs to pick up).
    let rebuilding = false;
    let pending = false;
    const rebuild = (): void => {
      if (rebuilding) {
        pending = true;
        return;
      }
      rebuilding = true;
      void bundleConsoleClient(dirs, assetsDir, 'dev')
        .catch((err: unknown) => console.error('[console] rebuild failed:', err instanceof Error ? err.message : err))
        .finally(() => {
          rebuilding = false;
          if (pending) {
            pending = false;
            rebuild();
          }
        });
    };
    const DEBOUNCE_MS = 200;
    let debounceTimer: NodeJS.Timeout | undefined;
    const scheduleRebuild = () => {
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(rebuild, DEBOUNCE_MS);
    };
    const watcher = watch(frameworkConsoleClientDir(), { recursive: true }, scheduleRebuild);
    const formsFile = path.join(dirs.generatedDir, 'console-forms.ts');
    const formsWatcher = existsSync(formsFile) ? watch(formsFile, scheduleRebuild) : null;

    const tailwindChild = cssEntry ? spawnTailwindWatch(cssEntry, path.join(assetsDir, 'main.css')) : null;

    return {
      stop: async () => {
        clearTimeout(debounceTimer);
        watcher.close();
        formsWatcher?.close();
        if (tailwindChild) await killChild(tailwindChild);
      },
    };
  }

  // prod: one-shot build, hashed filenames, manifest derived from the actual output.
  const jsOutput = await bundleConsoleClient(dirs, assetsDir, 'prod');
  manifest['main.js'] = path.relative(consoleDir, jsOutput.path);

  if (cssEntry) {
    const tmpCss = path.join(assetsDir, 'main.css');
    await runTailwindOnce(cssEntry, tmpCss, true);
    const hash = await hashFile(tmpCss);
    const hashedCss = path.join(assetsDir, `main-${hash}.css`);
    await rename(tmpCss, hashedCss);
    manifest['main.css'] = path.relative(consoleDir, hashedCss);
  }

  await writeFile(path.join(consoleDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return NOOP_HANDLE;
}

/** Edge-runtime groundwork only (see plan Context) — bundles a generated, statically-importing
 * server entry into one file. Does NOT change `ratchet serve`/`ratchet dev`'s runtime behavior,
 * which keep loading the registry dynamically via a native `import()` (Bun transpiles `.ts` on
 * the fly, no separate loader needed). `/api/auth` and `/api` are registered
 * before the console router so they keep precedence when `consolePath` is '/' (the console's own
 * catch-all would otherwise swallow every path — see `FrameworkConfig.consolePath`). */
export async function buildServerBundle(cwd: string, dirs: Dirs): Promise<void> {
  const entrySrc = [
    `// GENERATED by \`ratchet build\` — do not edit.`,
    `import { serve } from '@hono/node-server';`,
    `import { Hono } from 'hono';`,
    `import { drizzle } from 'drizzle-orm/postgres-js';`,
    `import postgres from 'postgres';`,
    `import { createApiRouter, buildRegistryMap, buildDomainSettingsRegistryMap } from '@egig/ratchet/router';`,
    `import { createAuthRouter } from '@egig/ratchet/auth';`,
    `import { createConsoleRouter } from '@egig/ratchet/console';`,
    `import { createNodeFsAssetSource } from '@egig/ratchet/console/node';`,
    `import * as registryModule from './registry.js';`,
    `import * as domainsModule from './domains.js';`,
    ``,
    `const connectionString = process.env.DATABASE_URL!;`,
    `const registry = buildRegistryMap(registryModule as Record<string, unknown>);`,
    `const domainSettingsRegistry = buildDomainSettingsRegistryMap(domainsModule as Record<string, unknown>);`,
    `const client = postgres(connectionString);`,
    `const db = drizzle(client);`,
    ``,
    `const app = new Hono();`,
    `app.route('/api/auth', createAuthRouter(db));`,
    `app.route('/api', createApiRouter(registry, db));`,
    `app.route(${JSON.stringify(dirs.consolePath)}, createConsoleRouter(createNodeFsAssetSource(${JSON.stringify(path.relative(cwd, dirs.generatedDir))}), registry, db, ${JSON.stringify(dirs.consolePath)}, domainSettingsRegistry));`,
    ``,
    `const port = Number(process.env.PORT ?? 3000);`,
    `serve({ fetch: app.fetch, port }, (info) => {`,
    `  console.log(\`ratchet listening on http://localhost:\${info.port}\`);`,
    `});`,
    ``,
  ].join('\n');

  const entryFile = path.join(dirs.generatedDir, 'server-entry.ts');
  await writeFile(entryFile, entrySrc, 'utf8');

  const result = await Bun.build({
    entrypoints: [entryFile],
    target: 'node',
    format: 'esm',
    packages: 'external',
    outdir: path.join(cwd, 'dist'),
    naming: 'server.js',
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('Bun.build failed to bundle the server entry');
  }
}
