import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * `drizzle-kit migrate` (unlike `generate`) only accepts a --config file, no direct
 * --schema/--out/--url flags — so we write one, derived from archet.config.ts, into the
 * same gitignored generatedDir as schema.ts/validators.ts/registry.ts (§6: a build artifact,
 * not something hand-edited).
 *
 * `schema`/`out` are written relative to `cwd`, not as absolute paths — matching every
 * drizzle-kit example in its own docs. Absolute paths here hit an internal drizzle-kit path-join
 * quirk (its own journal/snapshot validation concatenates a base path with `schema`/`out` rather
 * than resolving them, producing a mangled path like `.//Users/...` and an ENOENT) — relative
 * paths, resolved the conventional way, don't trigger it.
 */
export async function writeDrizzleKitConfig(cwd: string, generatedDir: string, migrationsDir: string): Promise<string> {
  await mkdir(generatedDir, { recursive: true });
  const schemaFile = path.join(generatedDir, 'schema.ts');
  const configFile = path.join(generatedDir, 'drizzle.config.ts');

  const relativeSchema = path.relative(cwd, schemaFile);
  const relativeOut = path.relative(cwd, migrationsDir);

  const src = [
    `// GENERATED by \`archet migrate\` — do not edit.`,
    `import { defineConfig } from 'drizzle-kit';`,
    ``,
    `export default defineConfig({`,
    `  dialect: 'postgresql',`,
    `  schema: ${JSON.stringify(relativeSchema)},`,
    `  out: ${JSON.stringify(relativeOut)},`,
    `  dbCredentials: { url: process.env.DATABASE_URL! },`,
    `});`,
    ``,
  ].join('\n');

  await writeFile(configFile, src, 'utf8');
  return configFile;
}
