const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.
// The single bundle every server entry point passes to \`createRatchetApp\`
// (@egig/ratchet/server): model + domain registries, and — when the
// \`src/web/\` site is opted into — its route manifest.

`;

/**
 * `.ratchet/app.ts` — collapses the two `import * as` lines + two `build*Map()` calls every entry
 * point used to write into one `import { bundle } from './.ratchet/app.js'`.
 *
 * @param hasWeb whether `generate` also wrote `app-routes.server.ts` (`routes/root.tsx` exists).
 */
export function generateAppBundleSource(hasWeb: boolean): string {
  const lines = [
    `import * as registryModule from './registry.js';`,
    `import * as domainsModule from './domains.js';`,
    `import { buildRegistryMap, buildDomainSettingsRegistryMap } from '@egig/ratchet/router';`,
    hasWeb ? `import { routes as webRoutes, resourceRouteIds } from './app-routes.server.js';` : null,
    ``,
    `export const bundle = {`,
    `  models: buildRegistryMap(registryModule as Record<string, unknown>),`,
    `  domains: buildDomainSettingsRegistryMap(domainsModule as Record<string, unknown>),`,
    hasWeb ? `  web: { routes: webRoutes, resourceRouteIds },` : null,
    `};`,
    ``,
  ].filter((line): line is string => line !== null);
  return HEADER + lines.join('\n');
}
