import type { ScannedDomain } from './scan-domains.js';
import { relativeImportSpecifier } from './paths.js';

const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.\n// Domain Settings registry — loaded once at boot by the console router's\n// /meta/domains* API (see src/console/router.ts).\n\n`;

export function generateDomainsSource(scanned: ScannedDomain[], generatedDir: string): string {
  const lines = scanned.map(({ exportName, filePath }) => {
    const modulePath = relativeImportSpecifier(generatedDir, filePath);
    return `export { ${exportName} } from '${modulePath}';`;
  });
  return HEADER + lines.join('\n') + (lines.length > 0 ? '\n' : '');
}
