import type { ScannedDomain } from './scan-domains.js';
import { relativeImportSpecifier } from './paths.js';

const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.\n// Domain Settings registry — loaded once at boot by the console router's\n// /meta/domains* API (see src/console/router.ts).\n\n`;

export function generateDomainsSource(scanned: ScannedDomain[], generatedDir: string): string {
  const lines = scanned.map(({ exportName, filePath, builtinPackage }) => {
    // builtins live inside the framework package, not the consuming project's tree — only a bare
    // specifier resolves correctly there (same reasoning as registry-gen.ts's `builtinPackage`).
    const modulePath = builtinPackage ?? relativeImportSpecifier(generatedDir, filePath);
    return `export { ${exportName} } from '${modulePath}';`;
  });
  return HEADER + lines.join('\n') + (lines.length > 0 ? '\n' : '');
}
