import type { ScannedFieldInput } from './scan-field-inputs.js';
import { relativeImportSpecifier } from './paths.js';

const HEADER =
  `// GENERATED by \`ratchet generate\` — do not edit.\n` +
  `// The console client's field-editor switch (src/console/client/fields.tsx) imports this file\n` +
  `// (via the \`ratchet:field-inputs\` virtual specifier a Bun.build plugin resolves here — see\n` +
  `// src/cli/build-console.ts) to know which field on which model gets a custom input instead of\n` +
  `// the one built into \`FieldInput\` for its \`kind\`.\n\n`;

function localName(modelName: string, fieldName: string): string {
  return `${modelName}_${fieldName}`.replace(/[^a-zA-Z0-9_$]/g, '_') + 'Input';
}

/** Emits \`fieldInputs\`: modelName -> fieldName -> component, one entry per \`*.input.tsx\` under
 * \`modelsDir\` (see scan-field-inputs.ts). Always written, even with zero field inputs, so the
 * bundle entry's import never dangles — mirrors \`generateCustomFormsSource\` (forms-gen.ts). */
export function generateFieldInputsSource(scanned: ScannedFieldInput[], generatedDir: string): string {
  const lines = [`import type { FieldRenderer } from '@egig/ratchet/console/client';`, ''];

  for (const { modelName, fieldName, filePath } of scanned) {
    lines.push(`import ${localName(modelName, fieldName)} from '${relativeImportSpecifier(generatedDir, filePath)}';`);
  }
  lines.push('');

  const byModel = new Map<string, ScannedFieldInput[]>();
  for (const entry of scanned) {
    const list = byModel.get(entry.modelName) ?? [];
    list.push(entry);
    byModel.set(entry.modelName, list);
  }

  lines.push('export const fieldInputs: Record<string, Record<string, FieldRenderer>> = {');
  for (const [modelName, entries] of byModel) {
    lines.push(`  ${JSON.stringify(modelName)}: {`);
    for (const { fieldName } of entries) {
      lines.push(`    ${JSON.stringify(fieldName)}: ${localName(modelName, fieldName)},`);
    }
    lines.push('  },');
  }
  lines.push('};');

  return HEADER + lines.join('\n') + '\n';
}
