import type { ScannedForm } from './scan-forms.js';
import { relativeImportSpecifier } from './paths.js';

const HEADER =
  `// GENERATED by \`ratchet generate\` — do not edit.\n` +
  `// The console client's bundle entry (src/console/client/main.tsx) imports this file (via the\n` +
  `// \`ratchet:custom-forms\` virtual specifier a Bun.build plugin resolves here — see\n` +
  `// src/cli/build-console.ts) to know which model gets a custom create/edit form instead of the\n` +
  `// generated one.\n\n`;

/** Emits \`customForms\`: a name -> component map, one entry per \`*.form.tsx\` under \`modelsDir\`
 * (see scan-forms.ts). Always written, even with zero custom forms, so the bundle entry's import
 * never dangles. */
export function generateCustomFormsSource(scanned: ScannedForm[], generatedDir: string): string {
  const lines = [`import type { ModelFormComponent } from '@egig/ratchet/console/client';`, ''];

  for (const { modelName, filePath } of scanned) {
    const localName = `${modelName.replace(/[^a-zA-Z0-9_$]/g, '_')}Form`;
    lines.push(`import ${localName} from '${relativeImportSpecifier(generatedDir, filePath)}';`);
  }
  lines.push('');

  lines.push('export const customForms: Record<string, ModelFormComponent> = {');
  for (const { modelName } of scanned) {
    const localName = `${modelName.replace(/[^a-zA-Z0-9_$]/g, '_')}Form`;
    lines.push(`  ${JSON.stringify(modelName)}: ${localName},`);
  }
  lines.push('};');

  return HEADER + lines.join('\n') + '\n';
}
