import type { ScannedModel } from './scan.js';
import { relativeImportSpecifier } from './paths.js';

const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.\n// A generic runtime router loads this file once at boot to build its\n// name -> ModelDefinition lookup map, rather than glob-importing models/**\n// (which doesn't survive bundling and isn't inspectable).\n\n`;

export function generateRegistrySource(scanned: ScannedModel[], generatedDir: string): string {
  const lines = scanned.map(({ exportName, filePath, builtinPackage, domain }) => {
    // builtins live inside the framework package, not the consuming project's tree — only a bare
    // specifier resolves correctly there (same reasoning as the `@egig/ratchet/core` import in validators-gen.ts).
    const modelPath = builtinPackage ?? relativeImportSpecifier(generatedDir, filePath);
    if (!domain) return `export { ${exportName} } from '${modelPath}';`;
    // a model's Domain (ADR 0001) is known only here, at codegen time — the model's own file has
    // no way to see which folder it was declared in — so it's merged onto `console` on the way
    // through the registry, the one place both the model object and its inferred Domain meet.
    const localName = `_${exportName}`;
    return [
      `import { ${exportName} as ${localName} } from '${modelPath}';`,
      `export const ${exportName} = { ...${localName}, console: { ...${localName}.console, domain: ${JSON.stringify(domain)} } };`,
    ].join('\n');
  });
  return HEADER + lines.join('\n') + '\n';
}
