import type { ScannedModel } from './scan.js';
import { relativeImportSpecifier } from './paths.js';

const HEADER = `// GENERATED by \`archet generate\` — do not edit.\n// A generic runtime router loads this file once at boot to build its\n// name -> ModelDefinition lookup map, rather than glob-importing models/**\n// (which doesn't survive bundling and isn't inspectable).\n\n`;

export function generateRegistrySource(scanned: ScannedModel[], generatedDir: string): string {
  const lines = scanned.map(({ exportName, filePath, builtin }) => {
    // builtins live inside the framework package, not the consuming project's tree — only a bare
    // specifier resolves correctly there (same reasoning as the `archet/core` import in validators-gen.ts).
    const modelPath = builtin ? 'archet/auth' : relativeImportSpecifier(generatedDir, filePath);
    return `export { ${exportName} } from '${modelPath}';`;
  });
  return HEADER + lines.join('\n') + '\n';
}
