import type { ScannedModel } from './scan.js';
import { relativeImportSpecifier } from './paths.js';

const HEADER = `// GENERATED by \`archet generate\` — do not edit.\n// A generic runtime router loads this file once at boot to build its\n// name -> ModelDefinition lookup map, rather than glob-importing models/**\n// (which doesn't survive bundling and isn't inspectable).\n\n`;

export function generateRegistrySource(scanned: ScannedModel[], generatedDir: string): string {
  const lines = scanned.map(({ exportName, filePath }) => {
    const modelPath = relativeImportSpecifier(generatedDir, filePath);
    return `export { ${exportName} } from '${modelPath}';`;
  });
  return HEADER + lines.join('\n') + '\n';
}
