import type { FieldDefinition } from '../core/field.js';
import type { ModelDefinition } from '../core/model.js';
import { toSnakeCase } from '../core/naming.js';
import type { ScannedModel } from './scan.js';

const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.\n// Source: models/**/*.model.ts\n\n`;

function tableVar(modelName: string): string {
  return `${modelName}Table`;
}

function columnExpr(key: string, f: FieldDefinition): string {
  const col = toSnakeCase(key);
  let expr: string;
  switch (f.kind) {
    case 'string':
      expr = f.maxLength !== undefined ? `varchar('${col}', { length: ${f.maxLength} })` : `varchar('${col}')`;
      break;
    case 'text':
      expr = `text('${col}')`;
      break;
    case 'integer':
      expr = `integer('${col}')`;
      break;
    case 'decimal':
      expr = `numeric('${col}', { precision: ${f.precision}, scale: ${f.scale} })`;
      break;
    case 'boolean':
      expr = `boolean('${col}')`;
      break;
    case 'datetime':
      // Q25: timestamptz, never bare timestamp — avoids the classic Postgres session-timezone footgun.
      expr = `timestamp('${col}', { withTimezone: true })`;
      break;
    case 'enum':
      // §4: varchar + CHECK, not native Postgres ENUM (see the check() constraint emitted below).
      expr = `varchar('${col}')`;
      break;
    case 'json':
      expr = `jsonb('${col}')`;
      break;
    case 'reference':
      // Q6: RESTRICT — refuse a hard-delete that would orphan referencing rows.
      expr = `uuid('${col}').references(() => ${tableVar(f.targetModel)}.id, { onDelete: 'restrict' })`;
      break;
  }
  if (f.required || f.default !== undefined) expr += '.notNull()';
  if (f.default !== undefined) expr += `.default(${JSON.stringify(f.default)})`;
  return expr;
}

function extraConfigLines(model: ModelDefinition): string[] {
  const lines: string[] = [];
  for (const [key, f] of Object.entries(model.fields)) {
    const col = toSnakeCase(key);
    if (f.indexed) {
      lines.push(`  index('${model.name}_${col}_idx').on(table.${key}),`);
    }
    if (f.unique) {
      // §4: partial unique index, not a plain UNIQUE — a soft-deleted row must not permanently
      // block reuse of its unique value.
      lines.push(
        `  uniqueIndex('${model.name}_${col}_unique_idx').on(table.${key}).where(sql` +
          '`' +
          '${table.deletedAt} IS NULL' +
          '`' +
          `),`,
      );
    }
    if (f.kind === 'enum') {
      const values = f.values.map((v) => `'${v.replace(/'/g, "''")}'`).join(', ');
      lines.push(
        `  check('${model.name}_${col}_check', sql` +
          '`' +
          '${table.' +
          key +
          '} IN (' +
          values +
          ')' +
          '`' +
          `),`,
      );
    }
  }
  return lines;
}

function emitTable(model: ModelDefinition): string {
  const varName = tableVar(model.name);
  const columnLines = [
    `  id: uuid('id').primaryKey(),`,
    `  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),`,
    `  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),`,
    `  deletedAt: timestamp('deleted_at', { withTimezone: true }),`,
    ...Object.entries(model.fields).map(([key, f]) => `  ${key}: ${columnExpr(key, f)},`),
  ];
  // Auto-indexed unconditionally: `id`, `createdAt`, `updatedAt` are treated as implicitly
  // sortable/filterable by the router (src/router/fields.ts) since a model author has no way to
  // declare `indexed: true` on a column they didn't author — "sort by most recent" needs a real
  // index to back it, not just a rule that allows the query.
  const extra = [`  index('${model.name}_created_at_idx').on(table.createdAt),`, `  index('${model.name}_updated_at_idx').on(table.updatedAt),`, ...extraConfigLines(model)];

  let src = `export const ${varName} = pgTable('${model.tableName}', {\n${columnLines.join('\n')}\n}`;
  if (extra.length > 0) {
    src += `, (table) => [\n${extra.join('\n')}\n]`;
  }
  src += `);\n`;
  return src;
}

export function generateSchemaSource(scanned: ScannedModel[]): string {
  const imports = [
    `import {`,
    `  pgTable,`,
    `  varchar,`,
    `  text,`,
    `  integer,`,
    `  numeric,`,
    `  boolean,`,
    `  timestamp,`,
    `  jsonb,`,
    `  uuid,`,
    `  index,`,
    `  uniqueIndex,`,
    `  check,`,
    `} from 'drizzle-orm/pg-core';`,
    `import { sql } from 'drizzle-orm';`,
    ``,
  ].join('\n');

  const tables = scanned.map(({ model }) => emitTable(model)).join('\n');

  return HEADER + imports + '\n' + tables;
}
