import type { FieldDefinition } from '../core/field.js';
import type { ModelDefinition } from '../core/model.js';
import { buildJunctionModel, junctionColumnsOf, manyToManyFieldsOf, type ManyToManyRelation } from '../core/many-to-many.js';
import { toSnakeCase } from '../core/naming.js';
import type { ScannedModel } from './scan.js';

const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.\n// Source: models/**/*.model.ts\n\n`;

function tableVar(modelName: string): string {
  return `${modelName}Table`;
}

function columnExpr(key: string, f: FieldDefinition): string {
  const col = toSnakeCase(key);
  let expr: string;
  switch (f.kind) {
    case 'string':
      expr = f.maxLength !== undefined ? `varchar('${col}', { length: ${f.maxLength} })` : `varchar('${col}')`;
      break;
    case 'text':
      expr = `text('${col}')`;
      break;
    case 'integer':
      expr = `integer('${col}')`;
      break;
    case 'decimal':
      expr = `numeric('${col}', { precision: ${f.precision}, scale: ${f.scale} })`;
      break;
    case 'boolean':
      expr = `boolean('${col}')`;
      break;
    case 'datetime':
      // Q25: timestamptz, never bare timestamp — avoids the classic Postgres session-timezone footgun.
      expr = `timestamp('${col}', { withTimezone: true })`;
      break;
    case 'enum':
      // §4: varchar + CHECK, not native Postgres ENUM (see the check() constraint emitted below).
      expr = `varchar('${col}')`;
      break;
    case 'json':
    case 'file':
      expr = `jsonb('${col}')`;
      break;
    case 'reference':
      // Q6: RESTRICT — refuse a hard-delete that would orphan referencing rows.
      expr = `uuid('${col}').references(() => ${tableVar(f.targetModel)}.id, { onDelete: 'restrict' })`;
      break;
    case 'modelRef':
    case 'actionRef':
    case 'fieldRef':
      // like 'enum': no length cap — real value enforcement is a per-request registry check,
      // not something the schema can express (see core/validation.ts).
      expr = `varchar('${col}')`;
      break;
    case 'manyToMany':
      // never reaches here — `emitTable` filters manyToMany fields out of `model.fields` before
      // calling `columnExpr` (there's no column to emit; the relation is backed by a separate
      // junction table, see `emitJunctionTable` below). Kept as an explicit throw, not folded into
      // a `default:`, so adding a future field kind without a case here is a compile error.
      throw new Error(`columnExpr: '${col}' is a manyToMany field — it has no column, see emitTable`);
  }
  if (f.required || f.default !== undefined) expr += '.notNull()';
  if (f.default !== undefined) expr += `.default(${JSON.stringify(f.default)})`;
  return expr;
}

function extraConfigLines(model: ModelDefinition): string[] {
  const lines: string[] = [];
  for (const [key, f] of Object.entries(model.fields)) {
    const col = toSnakeCase(key);
    if (f.indexed) {
      lines.push(`  index('${model.name}_${col}_idx').on(table.${key}),`);
    }
    if (f.unique) {
      // §4: partial unique index, not a plain UNIQUE — a soft-deleted row must not permanently
      // block reuse of its unique value.
      lines.push(
        `  uniqueIndex('${model.name}_${col}_unique_idx').on(table.${key}).where(sql` +
          '`' +
          '${table.deletedAt} IS NULL' +
          '`' +
          `),`,
      );
    }
    if (f.kind === 'enum') {
      const values = f.values.map((v) => `'${v.replace(/'/g, "''")}'`).join(', ');
      lines.push(
        `  check('${model.name}_${col}_check', sql` +
          '`' +
          '${table.' +
          key +
          '} IN (' +
          values +
          ')' +
          '`' +
          `),`,
      );
    }
  }
  return lines;
}

function emitTable(model: ModelDefinition, extraLines: string[] = []): string {
  const varName = tableVar(model.name);
  const columnLines = [
    `  id: uuid('id').primaryKey(),`,
    `  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),`,
    `  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),`,
    `  deletedAt: timestamp('deleted_at', { withTimezone: true }),`,
    // Q30: audit trail, not ownership — nullable (self-registration and other unauthenticated
    // creates have no actor to stamp) and RESTRICT like every other reference() column, but never
    // declarable via field.* and never touched by requireOwnsRow/updateRow.
    `  createdById: uuid('created_by_id').references(() => ${tableVar('users')}.id, { onDelete: 'restrict' }),`,
    // manyToMany has no column of its own — it's backed by a separate junction table instead
    // (see emitJunctionTable), so it's excluded here rather than passed to columnExpr.
    ...Object.entries(model.fields)
      .filter(([, f]) => f.kind !== 'manyToMany')
      .map(([key, f]) => `  ${key}: ${columnExpr(key, f)},`),
  ];
  // Auto-indexed unconditionally: `id`, `createdAt`, `updatedAt`, `createdById` are treated as
  // implicitly sortable/filterable by the router (src/router/fields.ts) since a model author has
  // no way to declare `indexed: true` on a column they didn't author — "sort by most recent" and
  // "show me what I created" both need a real index to back them, not just a rule that allows the
  // query.
  const extra = [
    `  index('${model.name}_created_at_idx').on(table.createdAt),`,
    `  index('${model.name}_updated_at_idx').on(table.updatedAt),`,
    `  index('${model.name}_created_by_id_idx').on(table.createdById),`,
    ...extraConfigLines(model),
    ...extraLines,
  ];

  let src = `export const ${varName} = pgTable('${model.tableName}', {\n${columnLines.join('\n')}\n}`;
  if (extra.length > 0) {
    src += `, (table) => [\n${extra.join('\n')}\n]`;
  }
  src += `);\n`;
  return src;
}

/** Emits the junction table backing one manyToMany relation — a normal table (see
 * `buildJunctionModel`, core/many-to-many.ts) plus one thing `field.*`'s own `unique: true` can't
 * express: a *compound* partial-unique index over both FK columns together, so the same pair can't
 * be attached twice while still allowing a re-attach after a prior soft-remove (same "partial
 * index, not plain UNIQUE" reasoning as `extraConfigLines`' per-field unique case above). */
function emitJunctionTable(relation: ManyToManyRelation): string {
  const junctionModel = buildJunctionModel(relation);
  const cols = junctionColumnsOf(relation);
  const compoundUniqueLine =
    `  uniqueIndex('${junctionModel.name}_unique_idx').on(table.${cols.sourceColumn}, table.${cols.targetColumn}).where(sql` +
    '`' +
    '${table.deletedAt} IS NULL' +
    '`' +
    `),`;
  return emitTable(junctionModel, [compoundUniqueLine]);
}

/** One shared, fixed-shape table backing every Domain's Domain Settings (ADR 0002) — a single
 * row per Domain, `values` a jsonb blob validated at the application layer against that Domain's
 * declared `field.*` schema (`core/validation.ts`'s `buildDomainSettingsSchema`), never against
 * per-domain Postgres columns. Emitted unconditionally, the same way the built-in auth tables
 * always exist regardless of whether a consuming app declares any Domain Settings of its own —
 * this keeps the table's own shape stable across `ratchet generate` runs even as domains are
 * added, renamed, or have fields added to their settings. */
function emitDomainSettingsTable(): string {
  return [
    `export const ratchetDomainSettingsTable = pgTable('ratchet_domain_settings', {`,
    `  domain: varchar('domain').primaryKey(),`,
    `  values: jsonb('values').notNull().default({}),`,
    `  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),`,
    `});\n`,
  ].join('\n');
}

export function generateSchemaSource(scanned: ScannedModel[]): string {
  const imports = [
    `import {`,
    `  pgTable,`,
    `  varchar,`,
    `  text,`,
    `  integer,`,
    `  numeric,`,
    `  boolean,`,
    `  timestamp,`,
    `  jsonb,`,
    `  uuid,`,
    `  index,`,
    `  uniqueIndex,`,
    `  check,`,
    `} from 'drizzle-orm/pg-core';`,
    `import { sql } from 'drizzle-orm';`,
    ``,
  ].join('\n');

  const tables = scanned.map(({ model }) => emitTable(model)).join('\n');

  // Every manyToMany field declared across every scanned model gets its own junction table — only
  // the declaring (source) side is scanned here, since the field key already namespaces the table
  // name (`core/many-to-many.ts`'s `junctionColumns`), so there's exactly one declaration per
  // relation to emit from, even though the relation is queryable from both sides at request time.
  const junctionTables = scanned
    .flatMap(({ model }) => manyToManyFieldsOf(model))
    .map((relation) => emitJunctionTable(relation))
    .join('\n');

  return HEADER + imports + '\n' + tables + '\n' + junctionTables + '\n' + emitDomainSettingsTable();
}
