import type { ScannedModel } from './scan.js';
import { capitalize, relativeImportSpecifier } from './paths.js';

const HEADER = `// GENERATED by \`ratchet generate\` — do not edit.\n\n`;

/**
 * Q14: an explicit, narrow exception to "codegen writes fully-printed source." A `field.json`
 * schema is an arbitrary live Zod value that can't in general be reconstructed as source text
 * (custom .refine()/.transform() etc.), so every model's Zod schema is built at runtime from the
 * live ModelDefinition (`buildCreateSchema`/`buildUpdateSchema`) and simply re-exported here under
 * a readable, per-model name — every other generated file in this project is fully printed source.
 *
 * `buildCreateSchema`/`buildUpdateSchema` are imported via the bare `@egig/ratchet/core` specifier,
 * not a computed relative filesystem path — this generated file lives inside a *consuming* project's
 * tree, so only Node's own module resolution (walking that project's `node_modules`) can reliably
 * find the framework, regardless of package-manager layout (flat/nested/pnpm-symlinked).
 */
export function generateValidatorsSource(scanned: ScannedModel[], generatedDir: string): string {
  const lines: string[] = [`import { buildCreateSchema, buildUpdateSchema } from '@egig/ratchet/core';`];

  for (const { exportName, filePath, builtin } of scanned) {
    const modelPath = builtin ? '@egig/ratchet/auth' : relativeImportSpecifier(generatedDir, filePath);
    lines.push(`import { ${exportName} } from '${modelPath}';`);
  }
  lines.push('');

  for (const { exportName, model } of scanned) {
    const pascal = capitalize(model.name);
    lines.push(`export const ${pascal}CreateSchema = buildCreateSchema(${exportName});`);
    lines.push(`export const ${pascal}UpdateSchema = buildUpdateSchema(${exportName});`);
  }

  return HEADER + lines.join('\n') + '\n';
}
