import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { FileStorageAdapter } from './storage.js';

function isEnoent(err: unknown): boolean {
  return err instanceof Error && (err as NodeJS.ErrnoException).code === 'ENOENT';
}

/** `key`s are always generated by the upload endpoint (`router/create-router.ts`), never taken
 * from a client — this guard exists as defense in depth against a key that somehow contains
 * path segments, not as the primary safeguard. */
function resolveWithinDir(dir: string, key: string): string {
  const filePath = path.join(dir, key);
  const rel = path.relative(dir, filePath);
  if (rel.startsWith('..') || path.isAbsolute(rel)) {
    throw new Error(`storage key '${key}' escapes the storage directory`);
  }
  return filePath;
}

function metaPath(filePath: string): string {
  return `${filePath}.meta.json`;
}

/** Default `FileStorageAdapter` for Node: stores each blob as a plain file under `dir`, plus a
 * `.meta.json` sidecar for its mime type (a bare file path has nowhere else to keep that).
 * Kept out of `ratchet/core` (which stays fs-free for edge callers) as its own subpath,
 * `ratchet/storage/node` — mirrors `ratchet/console/node`'s split for the same reason. */
export function createNodeFsStorageAdapter(dir: string): FileStorageAdapter {
  return {
    async put(key, data, opts) {
      const filePath = resolveWithinDir(dir, key);
      await mkdir(path.dirname(filePath), { recursive: true });
      await writeFile(filePath, data);
      await writeFile(metaPath(filePath), JSON.stringify({ mimeType: opts.mimeType }));
    },

    async get(key) {
      const filePath = resolveWithinDir(dir, key);
      try {
        const [data, metaRaw] = await Promise.all([readFile(filePath), readFile(metaPath(filePath), 'utf8')]);
        const meta = JSON.parse(metaRaw) as { mimeType: string };
        return { data, mimeType: meta.mimeType };
      } catch (err) {
        if (isEnoent(err)) return null;
        throw err;
      }
    },

    async delete(key) {
      const filePath = resolveWithinDir(dir, key);
      try {
        await Promise.all([rm(filePath), rm(metaPath(filePath))]);
      } catch (err) {
        if (!isEnoent(err)) throw err;
      }
    },
  };
}
