import { relativeImportSpecifier } from '../codegen/paths.js';
import type { RouteModule, RouteNode, ScannedRoutes } from './scan-routes.js';

/**
 * Turns a `ScannedRoutes` tree (scan-routes.ts) into the two generated manifests:
 *
 *  - `.ratchet/app-routes.server.ts` — the full `RouteObject[]`: real `loader`/`action`/`headers`
 *    refs, used by the SSR handler and the `.data` endpoint (server-side, never bundled for the
 *    browser, so nothing is stripped).
 *  - `.ratchet/app-routes.client.ts` — the browser tree: `Component`/`ErrorBoundary`/`handle`/
 *    `shouldRevalidate`, plus a single-fetch sentinel `loader`/`action` for any route whose module
 *    exports one (their real bodies are removed by the Bun.build `onLoad` transform —
 *    transform-server-exports.ts — so the sentinel is what tells `createBrowserRouter` to route
 *    that route's data through `dataStrategy`).
 */

const HEADER = '// GENERATED by `ratchet generate` — do not edit.\n';

function importAlias(id: string): string {
  return '_' + id.replace(/[^a-zA-Z0-9]/g, '_');
}

function keyForNode(node: RouteNode): string {
  if (node.index) return 'index: true';
  if (node.path !== undefined) return `path: ${JSON.stringify(node.path)}`;
  return '/* pathless layout */';
}

/** `handle` value expression, or null to omit — merges a module's own `handle` with `{ meta }`. */
function handleExpr(alias: string, mod: RouteModule): string | null {
  const hasHandle = mod.exports.includes('handle');
  const hasMeta = mod.exports.includes('meta');
  if (hasHandle && hasMeta) return `{ ...${alias}.handle, meta: ${alias}.meta }`;
  if (hasHandle) return `${alias}.handle`;
  if (hasMeta) return `{ meta: ${alias}.meta }`;
  return null;
}

function serverRouteFields(node: RouteNode): string[] {
  const fields = [`id: ${JSON.stringify(node.id)}`, keyForNode(node)];
  const mod = node.module;
  if (mod) {
    const a = importAlias(mod.id);
    if (mod.exports.includes('default')) fields.push(`Component: ${a}.default`);
    if (mod.exports.includes('loader')) fields.push(`loader: ${a}.loader`);
    if (mod.exports.includes('action')) fields.push(`action: ${a}.action`);
    if (mod.exports.includes('headers')) fields.push(`headers: ${a}.headers`);
    if (mod.exports.includes('ErrorBoundary')) fields.push(`ErrorBoundary: ${a}.ErrorBoundary`);
    if (mod.exports.includes('shouldRevalidate')) fields.push(`shouldRevalidate: ${a}.shouldRevalidate`);
    const h = handleExpr(a, mod);
    if (h) fields.push(`handle: ${h}`);
  }
  return fields;
}

function clientRouteFields(node: RouteNode): string[] {
  const fields = [`id: ${JSON.stringify(node.id)}`, keyForNode(node)];
  const mod = node.module;
  if (mod) {
    const a = importAlias(mod.id);
    if (mod.exports.includes('default')) fields.push(`Component: ${a}.default`);
    if (mod.exports.includes('loader')) fields.push(`loader: __sf(${JSON.stringify(node.id)})`);
    if (mod.exports.includes('action')) fields.push(`action: __sf(${JSON.stringify(node.id)})`);
    if (mod.exports.includes('ErrorBoundary')) fields.push(`ErrorBoundary: ${a}.ErrorBoundary`);
    if (mod.exports.includes('shouldRevalidate')) fields.push(`shouldRevalidate: ${a}.shouldRevalidate`);
    const h = handleExpr(a, mod);
    if (h) fields.push(`handle: ${h}`);
  }
  return fields;
}

function renderNodes(nodes: RouteNode[], fieldsOf: (n: RouteNode) => string[], indent: string): string {
  return nodes
    .map((node) => {
      const fields = fieldsOf(node);
      if (node.children && node.children.length > 0) {
        fields.push(`children: [\n${renderNodes(node.children, fieldsOf, indent + '  ')}\n${indent}  ]`);
      }
      return `${indent}  { ${fields.join(', ')} },`;
    })
    .join('\n');
}

function imports(scanned: ScannedRoutes, generatedDir: string): string {
  const all = [scanned.root!, ...scanned.modules];
  return all
    .map((mod) => `import * as ${importAlias(mod.id)} from ${JSON.stringify(relativeImportSpecifier(generatedDir, mod.file))};`)
    .join('\n');
}

export function generateServerRoutesSource(scanned: ScannedRoutes, generatedDir: string): string {
  const rootA = importAlias('root');
  const rootFields = ['id: "root"', 'path: "/"', `Component: ${rootA}.default`];
  if (scanned.root!.exports.includes('loader')) rootFields.push(`loader: ${rootA}.loader`);
  if (scanned.root!.exports.includes('action')) rootFields.push(`action: ${rootA}.action`);
  if (scanned.root!.exports.includes('headers')) rootFields.push(`headers: ${rootA}.headers`);
  rootFields.push(
    scanned.root!.exports.includes('ErrorBoundary')
      ? `ErrorBoundary: ${rootA}.ErrorBoundary`
      : 'ErrorBoundary: __DefaultRootErrorBoundary',
  );
  const rh = handleExpr(rootA, scanned.root!);
  if (rh) rootFields.push(`handle: ${rh}`);

  return [
    HEADER,
    `import type { RouteObject } from 'react-router';`,
    `import { DefaultRootErrorBoundary as __DefaultRootErrorBoundary } from '@egig/ratchet/web';`,
    imports(scanned, generatedDir),
    ``,
    `export const routes: RouteObject[] = [`,
    `  { ${rootFields.join(', ')}, children: [`,
    renderNodes(scanned.tree, serverRouteFields, '  '),
    `  ] },`,
    `];`,
    ``,
  ].join('\n');
}

export function generateClientRoutesSource(scanned: ScannedRoutes, generatedDir: string): string {
  const rootA = importAlias('root');
  const rootFields = ['id: "root"', 'path: "/"', `Component: ${rootA}.default`];
  if (scanned.root!.exports.includes('loader')) rootFields.push(`loader: __sf("root")`);
  if (scanned.root!.exports.includes('action')) rootFields.push(`action: __sf("root")`);
  rootFields.push(
    scanned.root!.exports.includes('ErrorBoundary')
      ? `ErrorBoundary: ${rootA}.ErrorBoundary`
      : 'ErrorBoundary: __DefaultRootErrorBoundary',
  );
  const rh = handleExpr(rootA, scanned.root!);
  if (rh) rootFields.push(`handle: ${rh}`);

  return [
    HEADER,
    `import type { RouteObject } from 'react-router';`,
    `import { DefaultRootErrorBoundary as __DefaultRootErrorBoundary, singleFetchHandler as __sf } from '@egig/ratchet/web';`,
    imports(scanned, generatedDir),
    ``,
    `export const routes: RouteObject[] = [`,
    `  { ${rootFields.join(', ')}, children: [`,
    renderNodes(scanned.tree, clientRouteFields, '  '),
    `  ] },`,
    `];`,
    ``,
  ].join('\n');
}
